In [2]:
import requests

In [3]:
import pandas as pd

In [4]:
initiating_year = pd.read_excel('initiating_year_total.xlsx')

In [5]:
main_file = pd.read_excel('main_pursuit_total.xlsx')

In [6]:
#other_violation = pd.read_excel('other_violation_total.xlsx')

In [7]:
suspect_year = pd.read_excel('suspect_year_total.xlsx')

In [8]:
terminating_info = pd.read_excel('terminating_info_total.xlsx')

In [9]:
total_injury = pd.read_excel('total_injury_total.xlsx')

In [10]:
shared_column = "Pursuit Number"

In [11]:
county_code_key = pd.read_csv('county code key.csv')
ncic_key = pd.read_csv('NCIC key.csv')

In [12]:
# Set the option to display all columns
pd.set_option('display.max_columns', None)

In [13]:
main_file['Initiating Agency NCIC'] = main_file['Initiating Agency NCIC'].astype(str)
ncic_key['Initiating Agency NCIC'] = ncic_key['Initiating Agency NCIC'].astype(str)

# Merging Data

In [14]:
result = main_file.copy()
result = result.merge(suspect_year, on=shared_column, how="left", suffixes=('', '_suspect'))
result = result.merge(total_injury, on=shared_column, how="left", suffixes=('', '_injury'))
result = result.merge(initiating_year, on=shared_column, how="left", suffixes=('', '_initiating'))
result = result.merge(terminating_info, on=shared_column, how="left", suffixes=('', '_terminating'))
result = result.merge(county_code_key, on= "County Code", how = "left", suffixes=('', '_cc'))
result = result.merge(ncic_key, on= "Initiating Agency NCIC", how = "left", suffixes=('', '_ncic')) 
#result = result.merge(other_violation, on=shared_column, how="left", suffixes=('', '_other'))

In [15]:
result['Suspect Ethnicity']

0         1.0
1        11.0
2         1.0
3         1.0
4         1.0
         ...
41180     1.0
41181    20.0
41182    11.0
41183     1.0
41184    11.0
Name: Suspect Ethnicity, Length: 41185, dtype: float64

In [16]:
# TODO: overwrite result['Suspect Ethnicity'] with a simple integer. Then, downstream
# you can more easily join your ethnicity "key" to this result DataFrame

In [17]:
columns_to_convert = ['County Code', 'Suspect Ethnicity', 'Suspect Gender', 'Suspect ID Type', 'Suspect Misc ID Type', 'Driver Disposition', 'Suspect DUI Status', 'Suspect Vehicle Year', 'Suspect Vehicle Make', 'Suspect Vehicle Type', 'Violation Type', 'Force Type Used to Terminate Pursuit', 'Terminating Event']
result[columns_to_convert] = result[columns_to_convert].astype('Int64')

In [18]:
result.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,Blank Not Used,NCIC Reporting This Rows Info,Date Area Became Involved,Time Area Became Involved,Time Involved Minutes,Distance Involved Miles,County Code,Supervisors ID Number (CHP Only),Time Supervisor Notified,Type of Supervisor Involvement,# of CHP Ground Units Involved,# of CHP Air Units Involved,# of Allied Ground Units Involved,# of Allied Air Units Involved,Max Freeway Speed,Max Surface Speed,Damage to Agency Equipment,Fatal Collision Count,Injury Collision Count,Property Damage Only Collision Count,Injuries due to Collision,Injuries After Pursuit,Did Area Initiate?,Did Area Terminate?,Spike Strip Count,PIT Count,Ramming Count,Boxxing in Count,Remote Engine Disabler Count,Other Forcible Stop Type Count,Other Forcible Stop Description,Area Menu Error Code,Injury Menu Error Code,Initiating Menu Error Code,Terminating Menu Error Code,susp_error,Critique Error Code,Supplemental,Status of Area Report,1st Digit of NCIC,2nd Digit of NCIC,Blank Not Used.1,Weather,Suspect Las Name,Suspect First Name,Suspect Middle Initial,Suspect DOB,Suspect Ethnicity,Suspect Gender,Suspect ID Type,Suspect ID State,Suspect Misc ID Type,Driver Disposition,Suspect DUI Status,Suspect Vehicle Year,Suspect Vehicle Make,Suspect Vehicle Type,Unidentified Vehicle Type,Officer Fatality from Collision,Suspect Fatality from Collision,Other Fatality from Collision,Officer Severe Injury from Collision,Suspect Severe Injury from Collision,Other Severe Injury from Collision,Officer Visible Injury from Collision,Suspect Visible Injury from Collision,Other Visible Injury from Collision,Officer Pain from Collision,Suspect Pain from Collision,Other Pain from Collision,Officer Fatality After Pursuit,Suspect Fatality After Pursuit,Suspect Fatality Self Inflicted After Pursuit,Other Fatality After Pursuit,Officer Severe Injury After Pursuit,Suspect Severe Injury After Pursuit,Suspect Severe Injury Self Inflicted After Pursuit,Other Severe Injury After Pursuit,Officer Visible Injury After Pursuit,Suspect Visible Injury After Pursuit,Suspect Self Inflicted Visible Injury After Pursuit,Other Visible Injury After Pursuit,Officer Pain After Pursuit,Suspect Pain After Pursuit,Suspect Pain Self Inflicted After Pursuit,Other Pain After Collision,Suspect Vehicle Passenger Fatality from Collision,Suspect Vehicle Passenger Severe Injury From Collision,Suspect Vehicle Passenger Visible Injury From Collision,Suspect Vehicle Passenger Pain Injury From Collision,Suspect Vehicle Passenger Fatality After Pursuit,Suspect Vehicle Passenger Self Inflicted Fatality After Pursuit,Suspect Vehicle Passenger Severe Injury After Pursuit,Suspect Vehicle Passenger Severe Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Visible Injury After Pursuit,Suspect Vehicle Passenger Visible Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Pain Injury After Pursuit,Suspect Vehicle Passenger Pain Self Inflicted After Pursuit,Initiating Violation,Violation Type,Blank Not Used_initiating,Blank Not Used.1_initiating,Most Serious Charged Upon Apprehension,Most Serious Charged Upon Apprehension Type,Blank Not Used_terminating,Other Violations Entered,Evading Section Charged,Force Type Used to Terminate Pursuit,Canine Involved,Blank Not Used.1_terminating,Terminating Event,Suspect Apprehended,Terminating NCIC_terminating,County,Agency Name,Agency City,Zipcode
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,Y,9550,2022-01-01,36,2,1,19,19931,36,2,1,0,0,0,0,75,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,UNKNOWN,UNKNOWN,,1900-01-01,1,0,0,NaN,0,6,5,2018,17,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,2800.2a VC,1,,,NaN,1,N,,10,N,9550,Los Angeles,SANTA FE SPRINGS AREA,SANTA FE SPRINGS,90670.0
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,Y,9525,2022-01-01,319,1,1,19,16989,320,2,1,0,0,0,0,50,N,0,0,1,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,Trejo,Alexis,M,1991-01-30,11,2,3,CA,0,5,4,2009,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5200 VC,3,,0.0,148a PC,2,,,2800.1a VC,1,N,,7,Y,9525,Los Angeles,BALDWIN PARK AREA,BALDWIN PARK,91706.0
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,Y,9456,2022-01-01,1333,5,7,20,16764,1333,1,1,0,0,0,0,100,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,4,N,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,0,42,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,NaN,,,,2800.2a VC,1,N,,10,N,9456,Madera,Oakhurst Area,Coarsegold,93614.0
3,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,9365,2022-01-01,2202,6,11,48,16515,2202,1,3,1,0,0,100,45,N,0,0,0,N,N,N,Y,0,0,0,0,0,0,0,N,N,N,N,N,N,NaN,DAF,9,3,N,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,2016,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245a PC,1,,0.0,245a PC,1,,Y,2800.2a VC,1,Y,,5,N,9365,Solano,FAIRFIELD POLICE DEPT.,FAIRFIELD,94533.0
4,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,4803,2022-01-01,2151,11,11,48,,,,0,1,1,0,0,1,,0,0,0,N,N,Y,N,0,0,0,0,0,0,NaN,N,N,N,N,N,N,,VF,4,8,,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,2016,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245a PC,1,,0.0,245a PC,1,,Y,2800.2a VC,1,Y,,5,N,9365,Solano,FAIRFIELD POLICE DEPT.,FAIRFIELD,94533.0

## Deduplicating Data

In [19]:
main_file['is_duplicate'] = main_file.duplicated(subset='Pursuit Number', keep = False)

In [20]:
main_file.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,Blank Not Used,NCIC Reporting This Rows Info,Date Area Became Involved,Time Area Became Involved,Time Involved Minutes,Distance Involved Miles,County Code,Supervisors ID Number (CHP Only),Time Supervisor Notified,Type of Supervisor Involvement,# of CHP Ground Units Involved,# of CHP Air Units Involved,# of Allied Ground Units Involved,# of Allied Air Units Involved,Max Freeway Speed,Max Surface Speed,Damage to Agency Equipment,Fatal Collision Count,Injury Collision Count,Property Damage Only Collision Count,Injuries due to Collision,Injuries After Pursuit,Did Area Initiate?,Did Area Terminate?,Spike Strip Count,PIT Count,Ramming Count,Boxxing in Count,Remote Engine Disabler Count,Other Forcible Stop Type Count,Other Forcible Stop Description,Area Menu Error Code,Injury Menu Error Code,Initiating Menu Error Code,Terminating Menu Error Code,susp_error,Critique Error Code,Supplemental,Status of Area Report,1st Digit of NCIC,2nd Digit of NCIC,Blank Not Used.1,Weather,is_duplicate
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,Y,9550,2022-01-01,36,2,1,19.0,19931,36,2,1,0,0,0,0,75,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,False
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,Y,9525,2022-01-01,319,1,1,19.0,16989,320,2,1,0,0,0,0,50,N,0,0,1,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,False
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,Y,9456,2022-01-01,1333,5,7,20.0,16764,1333,1,1,0,0,0,0,100,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,4,N,A,False
3,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,9365,2022-01-01,2202,6,11,48.0,16515,2202,1,3,1,0,0,100,45,N,0,0,0,N,N,N,Y,0,0,0,0,0,0,0,N,N,N,N,N,N,NaN,DAF,9,3,N,A,True
4,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,4803,2022-01-01,2151,11,11,48.0,,,,0,1,1,0,0,1,,0,0,0,N,N,Y,N,0,0,0,0,0,0,NaN,N,N,N,N,N,N,,VF,4,8,,A,True

In [21]:
main_file["is_duplicate"].value_counts()

is_duplicate
False    37789
True      3396
Name: count, dtype: int64

In [22]:
main_file['Pursuit Number'].nunique()

39240

In [23]:
type(result)

pandas.core.frame.DataFrame

In [24]:
print(result)

       Pursuit Number Initiating Date  Initiating Time State Status of Report  \
0               20221      2022-01-01               36    CA               F
1               20222      2022-01-01              319    CA               F
2               20223      2022-01-01             1333    UN               F
3               20224      2022-01-01             2151    CA               F
4               20224      2022-01-01             2151    CA               F
...               ...             ...              ...   ...              ...
41180       202413759      2024-08-22              212    UN               F
41181       202413760      2024-08-29                5    CA               F
41182       202413761      2024-09-07              122    CA               F
41183       202413762      2024-09-08              135    CA               F
41184       202413763      2024-09-08             2120    CA               F

      Initiating Agency NCIC Terminating NCIC Multi-Area/Agency Pursuit  \
0                       9550             9550                         N
1                       9525             9525                         N
2                       9456             9456                         N
3                       4803             9365                         Y
4                       4803             9365                         Y
...                      ...              ...                       ...
41180                   1942             1942                         N
41181                   1942             1942                         N
41182                   1942             1942                         N
41183                   1942             1942                         N
41184                   1942             1942                         N

      CHP Participation Requested  Requestor Name Blank Not Used  \
0                               N             NaN              Y
1                               N             NaN              Y
2                               N             NaN              Y
3                               Y  Sgt. Reed # S8              Y
4                               Y  Sgt. Reed # S8              Y
...                           ...             ...            ...
41180                                         NaN              Y
41181                                         NaN              Y
41182                                         NaN              Y
41183                                         NaN              Y
41184                                         NaN              Y

      NCIC Reporting This Rows Info Date Area Became Involved  \
0                              9550                2022-01-01
1                              9525                2022-01-01
2                              9456                2022-01-01
3                              9365                2022-01-01
4                              4803                2022-01-01
...                             ...                       ...
41180                          1942                2024-08-22
41181                          1942                2024-08-29
41182                          1942                2024-09-07
41183                          1942                2024-09-08
41184                          1942                2024-09-08

      Time Area Became Involved  Time Involved Minutes  \
0                            36                      2
1                           319                      1
2                          1333                      5
3                          2202                      6
4                          2151                     11
...                         ...                    ...
41180                       212                      2
41181                         5                      2
41182                       122                      7
41183                       135                      1
41184                      2120                      2

       Distance Involved Miles  County Code Supervisors ID Number (CHP Only)  \
0                            1           19                            19931
1                            1           19                            16989
2                            7           20                            16764
3                           11           48                            16515
4                           11           48
...                        ...          ...                              ...
41180                        4           19
41181                        2           19
41182                        6           19
41183                        1           19
41184                        2           19

      Time Supervisor Notified Type of Supervisor Involvement  \
0                           36                              2
1                          320                              2
2                         1333                              1
3                         2202                              1
4
...                        ...                            ...
41180
41181
41182
41183
41184

       # of CHP Ground Units Involved  # of CHP Air Units Involved  \
0                                   1                            0
1                                   1                            0
2                                   1                            0
3                                   3                            1
4                                   0                            1
...                               ...                          ...
41180                               0                            0
41181                               0                            0
41182                               0                            0
41183                               0                            0
41184                               0                            0

       # of Allied Ground Units Involved  # of Allied Air Units Involved  \
0                                      0                               0
1                                      0                               0
2                                      0                               0
3                                      0                               0
4                                      1                               0
...                                  ...                             ...
41180                                  1                               0
41181                                  1                               0
41182                                  5                               1
41183                                  1                               0
41184                                  1                               0

       Max Freeway Speed  Max Surface Speed Damage to Agency Equipment  \
0                      0                 75                          N
1                      0                 50                          N
2                      0                100                          N
3                    100                 45                          N
4                      0                  1
...                  ...                ...                        ...
41180                120                 50
41181                  0                 70
41182                  0                 70
41183                 80                 50
41184                  0                 70

       Fatal Collision Count  Injury Collision Count  \
0                          0                       0
1                          0                       0
2                          0                       0
3                          0                       0
4                          0                       0
...                      ...                     ...
41180                      0                       0
41181                      0                       0
41182                      0                       0
41183                      0                       0
41184                      0                       0

       Property Damage Only Collision Count Injuries due to Collision  \
0                                         0                         N
1                                         1                         N
2                                         0                         N
3                                         0                         N
4                                         0                         N
...                                     ...                       ...
41180                                     0                         N
41181                                     0                         N
41182                                     0                         N
41183                                     0                         N
41184                                     0                         N

      Injuries After Pursuit Did Area Initiate? Did Area Terminate?  \
0                          N                  Y                   Y
1                          N                  Y                   Y
2                          N                  Y                   Y
3                          N                  N                   Y
4                          N                  Y                   N
...                      ...                ...                 ...
41180                      N                  Y                   Y
41181                      N                  Y                   Y
41182                      N                  Y                   Y
41183                      N                  Y                   Y
41184                      N                  Y                   Y

       Spike Strip Count  PIT Count  Ramming Count  Boxxing in Count  \
0                      0          0              0                 0
1                      0          0              0                 0
2                      0          0              0                 0
3                      0          0              0                 0
4                      0          0              0                 0
...                  ...        ...            ...               ...
41180                  0          0              0                 0
41181                  0          0              0                 0
41182                  0          0              0                 0
41183                  0          0              0                 0
41184                  0          0              0                 0

       Remote Engine Disabler Count  Other Forcible Stop Type Count  \
0                                 0                               0
1                                 0                               0
2                                 0                               0
3                                 0                               0
4                                 0                               0
...                             ...                             ...
41180                             0                               0
41181                             0                               0
41182                             0                               0
41183                             0                               0
41184                             0                               0

      Other Forcible Stop Description Area Menu Error Code  \
0                                 NaN                    N
1                                 NaN                    N
2                                 NaN                    N
3                                   0                    N
4                                 NaN                    N
...                               ...                  ...
41180                             NaN                    N
41181                             NaN                    N
41182                             NaN                    N
41183                             NaN                    N
41184                             NaN                    N

      Injury Menu Error Code Initiating Menu Error Code  \
0                          N                          N
1                          N                          N
2                          N                          N
3                          N                          N
4                          N                          N
...                      ...                        ...
41180                      N                          N
41181                      N                          N
41182                      N                          N
41183                      N                          N
41184                      N                          N

      Terminating Menu Error Code susp_error Critique Error Code Supplemental  \
0                               N          N                   N          NaN
1                               N          N                   N          NaN
2                               N          N                   N          NaN
3                               N          N                   N          NaN
4                               N          N                   N
...                           ...        ...                 ...          ...
41180                           N          N                   N          NaN
41181                           N          N                   N          NaN
41182                           N          N                   N          NaN
41183                           N          N                   N          NaN
41184                           N          N                   N          NaN

      Status of Area Report 1st Digit of NCIC  2nd Digit of NCIC  \
0                       DAF                 9                  5
1                       DAF                 9                  5
2                       DAF                 9                  4
3                       DAF                 9                  3
4                       VF                  4                  8
...                     ...               ...                ...
41180                   VF                  1                  9
41181                   VF                  1                  9
41182                   VF                  1                  9
41183                   VF                  1                  9
41184                   VF                  1                  9

      Blank Not Used.1 Weather Suspect Las Name Suspect First Name  \
0                    N       A          UNKNOWN            UNKNOWN
1                    N       A            Trejo             Alexis
2                    N       A          Unknown                NaN
3                    N       A          Unknown                NaN
4                            A          Unknown                NaN
...                ...     ...              ...                ...
41180                        A              NaN                NaN
41181                        A              NaN                NaN
41182                        A              NaN                NaN
41183                        A              NaN                NaN
41184                        A              NaN                NaN

      Suspect Middle Initial Suspect DOB  Suspect Ethnicity  Suspect Gender  \
0                             1900-01-01                  1               0
1                          M  1991-01-30                 11               2
2                             1900-01-01                  1               0
3                             1900-01-01                  1               0
4                             1900-01-01                  1               0
...                      ...         ...                ...             ...
41180                         1900-01-01                  1               0
41181                         1900-01-01                 20               1
41182                         1998-03-03                 11               1
41183                         1900-01-01                  1               0
41184                         2006-09-20                 11               1

       Suspect ID Type Suspect ID State  Suspect Misc ID Type  \
0                    0              NaN                     0
1                    3               CA                     0
2                    0              NaN                     0
3                    0              NaN                     0
4                    0              NaN                     0
...                ...              ...                   ...
41180                0              NaN                     0
41181                0              NaN                     0
41182                0              NaN                     0
41183                0              NaN                     0
41184                0              NaN                     0

       Driver Disposition  Suspect DUI Status  Suspect Vehicle Year  \
0                       6                   5                  2018
1                       5                   4                  2009
2                       6                   5                     0
3                       6                   5                  2016
4                       6                   5                  2016
...                   ...                 ...                   ...
41180                   0                   5                     0
41181                   0                   1                     0
41182                   0                   5                     0
41183                   0                   5                     0
41184                   0                   5                     0

       Suspect Vehicle Make  Suspect Vehicle Type Unidentified Vehicle Type  \
0                        17                     2
1                         8                     2
2                        42                     2
3                         8                     2
4                         8                     2
...                     ...                   ...                       ...
41180                     1                     2
41181                     1                     3
41182                     1                     2
41183                     1                     2
41184                     1                     2

       Officer Fatality from Collision  Suspect Fatality from Collision  \
0                                  NaN                              NaN
1                                  NaN                              NaN
2                                  NaN                              NaN
3                                  NaN                              NaN
4                                  NaN                              NaN
...                                ...                              ...
41180                              NaN                              NaN
41181                              NaN                              NaN
41182                              NaN                              NaN
41183                              NaN                              NaN
41184                              NaN                              NaN

       Other Fatality from Collision  Officer Severe Injury from Collision  \
0                                NaN                                   NaN
1                                NaN                                   NaN
2                                NaN                                   NaN
3                                NaN                                   NaN
4                                NaN                                   NaN
...                              ...                                   ...
41180                            NaN                                   NaN

In [25]:
print(f"Total rows in main file: {len(main_file)}")
print(f"Total rows after merging: {len(result)}")

Total rows in main file: 41185
Total rows after merging: 41185

In [26]:
print(f"Main file duplicates: {main_file[shared_column].duplicated().sum()}")
print(f"Suspect year duplicates: {suspect_year[shared_column].duplicated().sum()}")
print(f"Total injury duplicates: {total_injury[shared_column].duplicated().sum()}")
print(f"Initiating year duplicates: {initiating_year[shared_column].duplicated().sum()}")
print(f"Terminating info duplicates: {terminating_info[shared_column].duplicated().sum()}")

Main file duplicates: 1945
Suspect year duplicates: 0
Total injury duplicates: 0
Initiating year duplicates: 0
Terminating info duplicates: 0

# I need to create a dictionary
# I need to remove duplicates

In [27]:
ethnicity = {
   1: 'Blank',
   2:  'Alaskan',
   3: 'Native American',
   4: 'Asian Indian',
   5: 'Black',
   6: 'Cambodian',
   7: 'Chinese',
   8: 'Filipino',
   9: 'Guamanian',
   10: 'Hawaiian',
   11: 'Hispanic',
   12: 'Japanese',
   13: 'Korean',
   14: 'Laotian',
   15: 'Other Asian',
   16: 'Other Pacific Islander',
   17: 'Samoan',
   18: 'Vietnamese',
   19: 'White',
   20: 'Other Not Listed'
}

In [28]:
result['suspect_ethnicity'] = result['Suspect Ethnicity'].map(ethnicity)

In [29]:
disposition = {
   0: 'Not Indicated',
   1:  'In Custody',
   2: 'Released',
   3: 'Turned over to allied agency',
   4: 'Deceased',
   5: 'Cited and Released',
   6: 'Suspect Outstanding'
}

In [30]:
result['driver_disposition'] = result['Driver Disposition'].map(disposition)

In [31]:
violation = {
   1: 'Felony',
   2:  'Misdemeanor',
   3: 'Infraction',
   4: 'Other'
}

In [32]:
result['violation_type'] = result['Violation Type'].map(violation)

In [33]:
term_event = {
   0: 'Not Reported',
   1:  'Suspect Vehicle Voluntarily Stopped',
   2: 'Forcible Stop',
   3: 'Suspect Vehicle Became Disabled',
   4: 'Patrol Vehicle Became Disabled',
   5: 'Pursuit Aborted by Law Enforcement Agency',
   6: 'Suspect Vehicle and Patrol Vehicle Collided',
   7: 'Suspect Vehicle Involved in a Collision',
   8: 'Patrol Vehicle Involved in a Collision',
   9: 'Blank',
   10: 'Suspect Vehicle Escaped Patrol Vehicle',
   11: 'Suspect Abandoned Vehicle and Fled on Foot',
   12: 'Other'
}

In [34]:
result['terminating_event'] = result['Terminating Event'].map(term_event)

In [35]:
result["Year"] = pd.to_datetime(result["Initiating Date"]).dt.year

In [36]:
result.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,Blank Not Used,NCIC Reporting This Rows Info,Date Area Became Involved,Time Area Became Involved,Time Involved Minutes,Distance Involved Miles,County Code,Supervisors ID Number (CHP Only),Time Supervisor Notified,Type of Supervisor Involvement,# of CHP Ground Units Involved,# of CHP Air Units Involved,# of Allied Ground Units Involved,# of Allied Air Units Involved,Max Freeway Speed,Max Surface Speed,Damage to Agency Equipment,Fatal Collision Count,Injury Collision Count,Property Damage Only Collision Count,Injuries due to Collision,Injuries After Pursuit,Did Area Initiate?,Did Area Terminate?,Spike Strip Count,PIT Count,Ramming Count,Boxxing in Count,Remote Engine Disabler Count,Other Forcible Stop Type Count,Other Forcible Stop Description,Area Menu Error Code,Injury Menu Error Code,Initiating Menu Error Code,Terminating Menu Error Code,susp_error,Critique Error Code,Supplemental,Status of Area Report,1st Digit of NCIC,2nd Digit of NCIC,Blank Not Used.1,Weather,Suspect Las Name,Suspect First Name,Suspect Middle Initial,Suspect DOB,Suspect Ethnicity,Suspect Gender,Suspect ID Type,Suspect ID State,Suspect Misc ID Type,Driver Disposition,Suspect DUI Status,Suspect Vehicle Year,Suspect Vehicle Make,Suspect Vehicle Type,Unidentified Vehicle Type,Officer Fatality from Collision,Suspect Fatality from Collision,Other Fatality from Collision,Officer Severe Injury from Collision,Suspect Severe Injury from Collision,Other Severe Injury from Collision,Officer Visible Injury from Collision,Suspect Visible Injury from Collision,Other Visible Injury from Collision,Officer Pain from Collision,Suspect Pain from Collision,Other Pain from Collision,Officer Fatality After Pursuit,Suspect Fatality After Pursuit,Suspect Fatality Self Inflicted After Pursuit,Other Fatality After Pursuit,Officer Severe Injury After Pursuit,Suspect Severe Injury After Pursuit,Suspect Severe Injury Self Inflicted After Pursuit,Other Severe Injury After Pursuit,Officer Visible Injury After Pursuit,Suspect Visible Injury After Pursuit,Suspect Self Inflicted Visible Injury After Pursuit,Other Visible Injury After Pursuit,Officer Pain After Pursuit,Suspect Pain After Pursuit,Suspect Pain Self Inflicted After Pursuit,Other Pain After Collision,Suspect Vehicle Passenger Fatality from Collision,Suspect Vehicle Passenger Severe Injury From Collision,Suspect Vehicle Passenger Visible Injury From Collision,Suspect Vehicle Passenger Pain Injury From Collision,Suspect Vehicle Passenger Fatality After Pursuit,Suspect Vehicle Passenger Self Inflicted Fatality After Pursuit,Suspect Vehicle Passenger Severe Injury After Pursuit,Suspect Vehicle Passenger Severe Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Visible Injury After Pursuit,Suspect Vehicle Passenger Visible Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Pain Injury After Pursuit,Suspect Vehicle Passenger Pain Self Inflicted After Pursuit,Initiating Violation,Violation Type,Blank Not Used_initiating,Blank Not Used.1_initiating,Most Serious Charged Upon Apprehension,Most Serious Charged Upon Apprehension Type,Blank Not Used_terminating,Other Violations Entered,Evading Section Charged,Force Type Used to Terminate Pursuit,Canine Involved,Blank Not Used.1_terminating,Terminating Event,Suspect Apprehended,Terminating NCIC_terminating,County,Agency Name,Agency City,Zipcode,suspect_ethnicity,driver_disposition,violation_type,terminating_event,Year
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,Y,9550,2022-01-01,36,2,1,19,19931,36,2,1,0,0,0,0,75,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,UNKNOWN,UNKNOWN,,1900-01-01,1,0,0,NaN,0,6,5,2018,17,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,2800.2a VC,1,,,NaN,1,N,,10,N,9550,Los Angeles,SANTA FE SPRINGS AREA,SANTA FE SPRINGS,90670.0,Blank,Suspect Outstanding,Infraction,Suspect Vehicle Escaped Patrol Vehicle,2022
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,Y,9525,2022-01-01,319,1,1,19,16989,320,2,1,0,0,0,0,50,N,0,0,1,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,Trejo,Alexis,M,1991-01-30,11,2,3,CA,0,5,4,2009,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5200 VC,3,,0.0,148a PC,2,,,2800.1a VC,1,N,,7,Y,9525,Los Angeles,BALDWIN PARK AREA,BALDWIN PARK,91706.0,Hispanic,Cited and Released,Infraction,Suspect Vehicle Involved in a Collision,2022
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,Y,9456,2022-01-01,1333,5,7,20,16764,1333,1,1,0,0,0,0,100,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,4,N,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,0,42,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,NaN,,,,2800.2a VC,1,N,,10,N,9456,Madera,Oakhurst Area,Coarsegold,93614.0,Blank,Suspect Outstanding,Infraction,Suspect Vehicle Escaped Patrol Vehicle,2022
3,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,9365,2022-01-01,2202,6,11,48,16515,2202,1,3,1,0,0,100,45,N,0,0,0,N,N,N,Y,0,0,0,0,0,0,0,N,N,N,N,N,N,NaN,DAF,9,3,N,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,2016,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245a PC,1,,0.0,245a PC,1,,Y,2800.2a VC,1,Y,,5,N,9365,Solano,FAIRFIELD POLICE DEPT.,FAIRFIELD,94533.0,Blank,Suspect Outstanding,Felony,Pursuit Aborted by Law Enforcement Agency,2022
4,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,4803,2022-01-01,2151,11,11,48,,,,0,1,1,0,0,1,,0,0,0,N,N,Y,N,0,0,0,0,0,0,NaN,N,N,N,N,N,N,,VF,4,8,,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,2016,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245a PC,1,,0.0,245a PC,1,,Y,2800.2a VC,1,Y,,5,N,9365,Solano,FAIRFIELD POLICE DEPT.,FAIRFIELD,94533.0,Blank,Suspect Outstanding,Felony,Pursuit Aborted by Law Enforcement Agency,2022

In [37]:
pursuit_counts = result.groupby("Pursuit Number").size()

In [38]:
unique_pursuits = pursuit_counts[pursuit_counts == 1].index

In [39]:
total_pursuit = result["Pursuit Number"].value_counts()
duplicated_pursuits = (total_pursuit > 1).sum()
print(total_pursuit.sum())
print(duplicated_pursuits)

41185
1451

In [40]:
pursuit_counts = result.groupby("Pursuit Number").size()
unique_pursuits = pursuit_counts[pursuit_counts == 1].index
deduplicated_table = result[result["Pursuit Number"].isin(unique_pursuits)]

In [41]:
len(deduplicated_table)

37789

In [42]:
41185-1451

39734

In [43]:
deduplicated_table["Pursuit Number"].value_counts()

Pursuit Number
20221        1
20222        1
20223        1
20225        1
20227        1
            ..
202413759    1
202413760    1
202413761    1
202413762    1
202413763    1
Name: count, Length: 37789, dtype: int64

In [44]:
total_duplicate_rows = result.duplicated("Pursuit Number", keep=False).sum()
print(total_duplicate_rows)

print(f"{len(result)} - {total_duplicate_rows} = {len(result) - total_duplicate_rows}")
print(f"Deduplicated table rows: {len(deduplicated_table)}")

3396
41185 - 3396 = 37789
Deduplicated table rows: 37789

## Analysis

In [45]:
deduplicated_table.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,Blank Not Used,NCIC Reporting This Rows Info,Date Area Became Involved,Time Area Became Involved,Time Involved Minutes,Distance Involved Miles,County Code,Supervisors ID Number (CHP Only),Time Supervisor Notified,Type of Supervisor Involvement,# of CHP Ground Units Involved,# of CHP Air Units Involved,# of Allied Ground Units Involved,# of Allied Air Units Involved,Max Freeway Speed,Max Surface Speed,Damage to Agency Equipment,Fatal Collision Count,Injury Collision Count,Property Damage Only Collision Count,Injuries due to Collision,Injuries After Pursuit,Did Area Initiate?,Did Area Terminate?,Spike Strip Count,PIT Count,Ramming Count,Boxxing in Count,Remote Engine Disabler Count,Other Forcible Stop Type Count,Other Forcible Stop Description,Area Menu Error Code,Injury Menu Error Code,Initiating Menu Error Code,Terminating Menu Error Code,susp_error,Critique Error Code,Supplemental,Status of Area Report,1st Digit of NCIC,2nd Digit of NCIC,Blank Not Used.1,Weather,Suspect Las Name,Suspect First Name,Suspect Middle Initial,Suspect DOB,Suspect Ethnicity,Suspect Gender,Suspect ID Type,Suspect ID State,Suspect Misc ID Type,Driver Disposition,Suspect DUI Status,Suspect Vehicle Year,Suspect Vehicle Make,Suspect Vehicle Type,Unidentified Vehicle Type,Officer Fatality from Collision,Suspect Fatality from Collision,Other Fatality from Collision,Officer Severe Injury from Collision,Suspect Severe Injury from Collision,Other Severe Injury from Collision,Officer Visible Injury from Collision,Suspect Visible Injury from Collision,Other Visible Injury from Collision,Officer Pain from Collision,Suspect Pain from Collision,Other Pain from Collision,Officer Fatality After Pursuit,Suspect Fatality After Pursuit,Suspect Fatality Self Inflicted After Pursuit,Other Fatality After Pursuit,Officer Severe Injury After Pursuit,Suspect Severe Injury After Pursuit,Suspect Severe Injury Self Inflicted After Pursuit,Other Severe Injury After Pursuit,Officer Visible Injury After Pursuit,Suspect Visible Injury After Pursuit,Suspect Self Inflicted Visible Injury After Pursuit,Other Visible Injury After Pursuit,Officer Pain After Pursuit,Suspect Pain After Pursuit,Suspect Pain Self Inflicted After Pursuit,Other Pain After Collision,Suspect Vehicle Passenger Fatality from Collision,Suspect Vehicle Passenger Severe Injury From Collision,Suspect Vehicle Passenger Visible Injury From Collision,Suspect Vehicle Passenger Pain Injury From Collision,Suspect Vehicle Passenger Fatality After Pursuit,Suspect Vehicle Passenger Self Inflicted Fatality After Pursuit,Suspect Vehicle Passenger Severe Injury After Pursuit,Suspect Vehicle Passenger Severe Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Visible Injury After Pursuit,Suspect Vehicle Passenger Visible Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Pain Injury After Pursuit,Suspect Vehicle Passenger Pain Self Inflicted After Pursuit,Initiating Violation,Violation Type,Blank Not Used_initiating,Blank Not Used.1_initiating,Most Serious Charged Upon Apprehension,Most Serious Charged Upon Apprehension Type,Blank Not Used_terminating,Other Violations Entered,Evading Section Charged,Force Type Used to Terminate Pursuit,Canine Involved,Blank Not Used.1_terminating,Terminating Event,Suspect Apprehended,Terminating NCIC_terminating,County,Agency Name,Agency City,Zipcode,suspect_ethnicity,driver_disposition,violation_type,terminating_event,Year
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,Y,9550,2022-01-01,36,2,1,19,19931,36,2,1,0,0,0,0,75,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,UNKNOWN,UNKNOWN,,1900-01-01,1,0,0,NaN,0,6,5,2018,17,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,2800.2a VC,1,,,NaN,1,N,,10,N,9550,Los Angeles,SANTA FE SPRINGS AREA,SANTA FE SPRINGS,90670.0,Blank,Suspect Outstanding,Infraction,Suspect Vehicle Escaped Patrol Vehicle,2022
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,Y,9525,2022-01-01,319,1,1,19,16989,320,2,1,0,0,0,0,50,N,0,0,1,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,Trejo,Alexis,M,1991-01-30,11,2,3,CA,0,5,4,2009,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5200 VC,3,,0.0,148a PC,2,,,2800.1a VC,1,N,,7,Y,9525,Los Angeles,BALDWIN PARK AREA,BALDWIN PARK,91706.0,Hispanic,Cited and Released,Infraction,Suspect Vehicle Involved in a Collision,2022
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,Y,9456,2022-01-01,1333,5,7,20,16764,1333,1,1,0,0,0,0,100,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,4,N,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,0,42,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,NaN,,,,2800.2a VC,1,N,,10,N,9456,Madera,Oakhurst Area,Coarsegold,93614.0,Blank,Suspect Outstanding,Infraction,Suspect Vehicle Escaped Patrol Vehicle,2022
5,20225,2022-01-01,2316,CA,F,9335,9335,N,N,NaN,Y,9335,2022-01-01,2316,10,11,38,16010,2316,2,2,0,0,1,100,60,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,3,N,A,UNKNOWN,NaN,,1900-01-01,5,1,0,NaN,0,6,5,2010,14,5,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21658a VC,3,,0.0,2800.2a VC,1,,,2800.2a VC,1,N,,5,N,9335,San Francisco,SAN FRANCISCO AREA,SAN FRANCISCO,94103.0,Black,Suspect Outstanding,Infraction,Pursuit Aborted by Law Enforcement Agency,2022
9,20227,2022-01-01,834,UN,F,9375,9375,N,N,NaN,Y,9375,2022-01-01,834,2,2,1,21936,834,1,2,0,0,0,100,90,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,3,N,A,UNK,UNK,,1900-01-01,1,0,0,NaN,0,6,5,0,17,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,2800.2a VC,1,,,2800.2a VC,1,N,,5,N,9375,Alameda,CASTRO VALLEY AREA,CASTRO VALLEY,94546.0,Blank,Suspect Outstanding,Infraction,Pursuit Aborted by Law Enforcement Agency,2022

In [50]:
death_count = deduplicated_table.groupby("Agency Name")[["Fatal Collision Count", "Injury Collision Count"]].sum()
death_count = death_count.reset_index()
death_count.columns = ["Agency Name", "Total Fatal Collisions", "Total Injury Collisions"]
death_count = death_count[death_count["Total Injury Collisions"] > 1]
death_count.sort_values("Total Injury Collisions", ascending = False)

,Agency Name,Total Fatal Collisions,Total Injury Collisions
251,LOS ANGELES POLICE DEPT.,6,274
401,SAN DIEGO POLICE DEPT.,4,108
250,LOS ANGELES COUNTY SHERIFF,4,101
395,SAN BERNARDINO COUNTY SHERIFF,2,60
388,SACRAMENTO POLICE DEPT.,0,58
...,...,...,...
470,SOUTH SAN FRANCISCO POLICE DEPT.,0,2
78,CARLSBAD POLICE DEPT.,0,2
62,BUTTONWILLOW AREA,0,2
80,CASTRO VALLEY AREA,0,2
492,TRINITY RIVER AREA,0,2

## make injury and death rate

In [52]:
agency_counts = deduplicated_table.groupby("Agency Name").size().sort_values(ascending =False)

In [53]:
#agency_counts = agency_counts[agency_counts > ].sort_values(ascending = False)

In [54]:
print(agency_counts)

Agency Name
LOS ANGELES POLICE DEPT.             1865
LOS ANGELES COUNTY SHERIFF           1756
SAN BERNARDINO COUNTY SHERIFF         863
SAN DIEGO POLICE DEPT.                858
HAYWARD AREA                          842
                                     ...
FOWLER POLICE DEPT.                     1
UC SANTA BARBARA                        1
UC SAN FRANCISCO                        1
VAL VERDE UNIFIED SCHOOL DISTRICT       1
ALPINE COUNTY SHERIFF                   1
Length: 551, dtype: int64

In [55]:
county_by_year = deduplicated_table.groupby(["County", "Year"]).size().sort_values(ascending =False)

In [56]:
print(county_by_year)

County          Year
Los Angeles     2024    3152
                2023    2972
                2022    2682
Alameda         2024    1329
San Bernardino  2024    1001
                        ...
Alpine          2023       2
Modoc           2024       2
Mono            2023       2
Sierra          2023       2
Plumas          2023       1
Length: 171, dtype: int64

In [57]:
%pip install altair

Requirement already satisfied: altair in /usr/local/python/3.12.1/lib/python3.12/site-packages (6.0.0)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (from altair) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /home/codespace/.local/lib/python3.12/site-packages (from altair) (4.24.0)
Requirement already satisfied: narwhals>=1.27.1 in /home/codespace/.local/lib/python3.12/site-packages (from altair) (1.46.0)
Requirement already satisfied: packaging in /home/codespace/.local/lib/python3.12/site-packages (from altair) (25.0)
Requirement already satisfied: typing-extensions>=4.12.0 in /home/codespace/.local/lib/python3.12/site-packages (from altair) (4.14.1)
Requirement already satisfied: attrs>=22.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=3.0->altair) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=3.0->altair) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=3.0->altair) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=3.0->altair) (0.26.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.local/lib/python3.12/site-packages (from jinja2->altair) (3.0.2)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [58]:
import altair as alt

In [59]:
county_counts = deduplicated_table.groupby("County").size().sort_values(ascending =False).reset_index(name='Number of Pursuits')

In [60]:
print(county_counts)

             County  Number of Pursuits
0       Los Angeles                8806
1           Alameda                3253
2    San Bernardino                2817
3         San Diego                2508
4        Sacramento                1914
5            Orange                1857
6         Riverside                1690
7      Contra Costa                1454
8       San Joaquin                1424
9              Kern                1359
10           Fresno                 978
11      Santa Clara                 829
12           Solano                 823
13          Venture                 671
14    San Francisco                 639
15           Tulare                 632
16       Stanislaus                 518
17        San Mateo                 504
18           Merced                 425
19           Sonoma                 417
20         Monterey                 415
21    Santa Barbara                 390
22       Santa Cruz                 319
23            Butte                 282
24            Kings                 219
25           Shasta                 218
26         Humboldt                 215
27           Placer                 189
28            Marin                 183
29  San Luis Obispo                 165
30             Yolo                 149
31             Napa                 141
32           Sutter                 129
33           Madera                 121
34        Mendocino                 109
35             Yuba                 108
36         Imperial                  97
37         Tuolumne                  87
38        Del Norte                  81
39        El Dorado                  77
40             Lake                  67
41         Siskiyou                  66
42           Tehama                  56
43           Colusa                  53
44           Nevada                  49
45        Calaveras                  46
46       San Benito                  45
47           Amador                  32
48            Glenn                  31
49           Lassen                  31
50             Inyo                  22
51          Trinity                  20
52             Mono                  18
53         Mariposa                  15
54           Plumas                  12
55            Modoc                   8
56           Alpine                   4
57           Sierra                   2

In [61]:
alt.Chart(county_counts).mark_bar().encode(
    x = "County",
    y = "Number of Pursuits"
)

alt.Chart(...)

In [62]:
pop = pd.read_csv("ca county population.csv")

In [63]:
final_county = pd.merge(county_counts, pop, on="County")

In [64]:
print(final_county)

             County  Number of Pursuits Population
0       Los Angeles                8806  9,745,821
1           Alameda                3253  1,640,965
2         San Diego                2508  3,289,481
3        Sacramento                1914  1,598,160
4            Orange                1857  3,161,162
5         Riverside                1690  2,504,370
6      Contra Costa                1454  1,165,027
7       San Joaquin                1424    805,966
8              Kern                1359    918,823
9            Fresno                 978  1,020,377
10      Santa Clara                 829  1,902,372
11           Solano                 823    451,962
12    San Francisco                 639    820,284
13           Tulare                 632    480,860
14       Stanislaus                 518    554,434
15        San Mateo                 504    736,548
16           Merced                 425    294,403
17           Sonoma                 417    484,046
18         Monterey                 415    436,105
19    Santa Barbara                 390    444,436
20       Santa Cruz                 319    263,985
21            Butte                 282    207,691
22            Kings                 219    153,657
23           Shasta                 218    180,916
24         Humboldt                 215    133,801
25           Placer                 189    425,620
26            Marin                 183    256,416
27  San Luis Obispo                 165    282,128
28             Yolo                 149    223,836
29             Napa                 141    133,554
30           Sutter                 129     98,561
31           Madera                 121    163,083
32        Mendocino                 109     89,519
33             Yuba                 108     85,833
34         Imperial                  97    180,692
35         Tuolumne                  87     53,989
36        Del Norte                  81     26,779
37        El Dorado                  77    192,778
38             Lake                  67     67,979
39         Siskiyou                  66     43,062
40           Tehama                  56     64,893
41           Colusa                  53     22,040
42           Nevada                  49    102,212
43        Calaveras                  46     46,543
44       San Benito                  45     68,405
45           Amador                  32     41,770
46            Glenn                  31     28,288
47           Lassen                  31     29,193
48             Inyo                  22     18,593
49          Trinity                  20     15,701
50             Mono                  18     13,084
51         Mariposa                  15     17,046
52           Plumas                  12     19,129
53            Modoc                   8      8,561
54           Alpine                   4      1,131
55           Sierra                   2      3,169

In [65]:
final_county.dtypes

County                object
Number of Pursuits     int64
Population            object
dtype: object

In [66]:
final_county['Population'] = final_county['Population'].str.replace(',', '').astype(int)

In [67]:
final_county["pursuit_rate"] = (final_county["Number of Pursuits"] / final_county["Population"]) * 10_000

In [68]:
final_county.sort_values("pursuit_rate", ascending = False)

             County  Number of Pursuits  Population  pursuit_rate
54           Alpine                   4        1131     35.366932
36        Del Norte                  81       26779     30.247582
41           Colusa                  53       22040     24.047187
1           Alameda                3253     1640965     19.823701
11           Solano                 823      451962     18.209495
7       San Joaquin                1424      805966     17.668239
35         Tuolumne                  87       53989     16.114394
24         Humboldt                 215      133801     16.068639
39         Siskiyou                  66       43062     15.326738
8              Kern                1359      918823     14.790662
16           Merced                 425      294403     14.435994
22            Kings                 219      153657     14.252523
50             Mono                  18       13084     13.757261
21            Butte                 282      207691     13.577863
13           Tulare                 632      480860     13.143119
30           Sutter                 129       98561     13.088341
49          Trinity                  20       15701     12.738042
33             Yuba                 108       85833     12.582573
6      Contra Costa                1454     1165027     12.480397
32        Mendocino                 109       89519     12.176186
20       Santa Cruz                 319      263985     12.084020
23           Shasta                 218      180916     12.049791
3        Sacramento                1914     1598160     11.976273
48             Inyo                  22       18593     11.832410
46            Glenn                  31       28288     10.958710
47           Lassen                  31       29193     10.618984
29             Napa                 141      133554     10.557527
43        Calaveras                  46       46543      9.883334
38             Lake                  67       67979      9.855985
9            Fresno                 978     1020377      9.584693
18         Monterey                 415      436105      9.516057
53            Modoc                   8        8561      9.344703
14       Stanislaus                 518      554434      9.342861
0       Los Angeles                8806     9745821      9.035668
51         Mariposa                  15       17046      8.799718
19    Santa Barbara                 390      444436      8.775167
40           Tehama                  56       64893      8.629590
17           Sonoma                 417      484046      8.614884
12    San Francisco                 639      820284      7.789985
45           Amador                  32       41770      7.661001
2         San Diego                2508     3289481      7.624303
31           Madera                 121      163083      7.419535
26            Marin                 183      256416      7.136840
15        San Mateo                 504      736548      6.842731
5         Riverside                1690     2504370      6.748204
28             Yolo                 149      223836      6.656659
44       San Benito                  45       68405      6.578466
55           Sierra                   2        3169      6.311139
52           Plumas                  12       19129      6.273198
4            Orange                1857     3161162      5.874422
27  San Luis Obispo                 165      282128      5.848409
34         Imperial                  97      180692      5.368251
42           Nevada                  49      102212      4.793958
25           Placer                 189      425620      4.440581
10      Santa Clara                 829     1902372      4.357718
37        El Dorado                  77      192778      3.994232

In [69]:
bay_area_counties = ['Alameda', 'Contra Costa', 'Marin', 'Napa', 'San Francisco', 
 'San Mateo', 'Santa Clara', 'Solano', 'Sonoma']

bay_area = final_county[final_county['County'].isin(bay_area_counties)]
bay_area.sort_values("pursuit_rate", ascending = False)

           County  Number of Pursuits  Population  pursuit_rate
1         Alameda                3253     1640965     19.823701
11         Solano                 823      451962     18.209495
6    Contra Costa                1454     1165027     12.480397
29           Napa                 141      133554     10.557527
17         Sonoma                 417      484046      8.614884
12  San Francisco                 639      820284      7.789985
26          Marin                 183      256416      7.136840
15      San Mateo                 504      736548      6.842731
10    Santa Clara                 829     1902372      4.357718

must pull out each year