In [4]:
import requests

In [5]:
import pandas as pd

In [6]:
initiating_year = pd.read_excel('initiating_year_total.xlsx')

In [7]:
main_file = pd.read_excel('main_pursuit_total.xlsx')

In [8]:
#other_violation = pd.read_excel('other_violation_total.xlsx')

In [9]:
suspect_year = pd.read_excel('suspect_year_total.xlsx')

In [10]:
terminating_info = pd.read_excel('terminating_info_total.xlsx')

In [11]:
total_injury = pd.read_excel('total_injury_total.xlsx')

In [12]:
shared_column = "Pursuit Number"

In [13]:
# Set the option to display all columns
pd.set_option('display.max_columns', None)

In [14]:
result = main_file.copy()
result = result.merge(suspect_year, on=shared_column, how="left", suffixes=('', '_suspect'))
result = result.merge(total_injury, on=shared_column, how="left", suffixes=('', '_injury'))
result = result.merge(initiating_year, on=shared_column, how="left", suffixes=('', '_initiating'))
result = result.merge(terminating_info, on=shared_column, how="left", suffixes=('', '_terminating'))
#result = result.merge(other_violation, on=shared_column, how="left", suffixes=('', '_other'))

In [15]:
result['Suspect Ethnicity']

0         1.0
1        11.0
2         1.0
3         1.0
4         1.0
         ...
41180     1.0
41181    20.0
41182    11.0
41183     1.0
41184    11.0
Name: Suspect Ethnicity, Length: 41185, dtype: float64

In [16]:
# TODO: overwrite result['Suspect Ethnicity'] with a simple integer. Then, downstream
# you can more easily join your ethnicity "key" to this result DataFrame

In [17]:
columns_to_convert = ['County Code', 'Suspect Ethnicity', 'Suspect Gender', 'Suspect ID Type', 'Suspect Misc ID Type', 'Driver Disposition', 'Suspect DUI Status', 'Suspect Vehicle Year', 'Suspect Vehicle Make', 'Suspect Vehicle Type', 'Violation Type', 'Force Type Used to Terminate Pursuit', 'Terminating Event']
result[columns_to_convert] = result[columns_to_convert].astype('Int64')

In [20]:
result.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,Blank Not Used,NCIC Reporting This Rows Info,Date Area Became Involved,Time Area Became Involved,Time Involved Minutes,Distance Involved Miles,County Code,Supervisors ID Number (CHP Only),Time Supervisor Notified,Type of Supervisor Involvement,# of CHP Ground Units Involved,# of CHP Air Units Involved,# of Allied Ground Units Involved,# of Allied Air Units Involved,Max Freeway Speed,Max Surface Speed,Damage to Agency Equipment,Fatal Collision Count,Injury Collision Count,Property Damage Only Collision Count,Injuries due to Collision,Injuries After Pursuit,Did Area Initiate?,Did Area Terminate?,Spike Strip Count,PIT Count,Ramming Count,Boxxing in Count,Remote Engine Disabler Count,Other Forcible Stop Type Count,Other Forcible Stop Description,Area Menu Error Code,Injury Menu Error Code,Initiating Menu Error Code,Terminating Menu Error Code,susp_error,Critique Error Code,Supplemental,Status of Area Report,1st Digit of NCIC,2nd Digit of NCIC,Blank Not Used.1,Weather,Suspect Las Name,Suspect First Name,Suspect Middle Initial,Suspect DOB,Suspect Ethnicity,Suspect Gender,Suspect ID Type,Suspect ID State,Suspect Misc ID Type,Driver Disposition,Suspect DUI Status,Suspect Vehicle Year,Suspect Vehicle Make,Suspect Vehicle Type,Unidentified Vehicle Type,Officer Fatality from Collision,Suspect Fatality from Collision,Other Fatality from Collision,Officer Severe Injury from Collision,Suspect Severe Injury from Collision,Other Severe Injury from Collision,Officer Visible Injury from Collision,Suspect Visible Injury from Collision,Other Visible Injury from Collision,Officer Pain from Collision,Suspect Pain from Collision,Other Pain from Collision,Officer Fatality After Pursuit,Suspect Fatality After Pursuit,Suspect Fatality Self Inflicted After Pursuit,Other Fatality After Pursuit,Officer Severe Injury After Pursuit,Suspect Severe Injury After Pursuit,Suspect Severe Injury Self Inflicted After Pursuit,Other Severe Injury After Pursuit,Officer Visible Injury After Pursuit,Suspect Visible Injury After Pursuit,Suspect Self Inflicted Visible Injury After Pursuit,Other Visible Injury After Pursuit,Officer Pain After Pursuit,Suspect Pain After Pursuit,Suspect Pain Self Inflicted After Pursuit,Other Pain After Collision,Suspect Vehicle Passenger Fatality from Collision,Suspect Vehicle Passenger Severe Injury From Collision,Suspect Vehicle Passenger Visible Injury From Collision,Suspect Vehicle Passenger Pain Injury From Collision,Suspect Vehicle Passenger Fatality After Pursuit,Suspect Vehicle Passenger Self Inflicted Fatality After Pursuit,Suspect Vehicle Passenger Severe Injury After Pursuit,Suspect Vehicle Passenger Severe Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Visible Injury After Pursuit,Suspect Vehicle Passenger Visible Self Inflicted Injury After Pursuit,Suspect Vehicle Passenger Pain Injury After Pursuit,Suspect Vehicle Passenger Pain Self Inflicted After Pursuit,Initiating Violation,Violation Type,Blank Not Used_initiating,Blank Not Used.1_initiating,Most Serious Charged Upon Apprehension,Most Serious Charged Upon Apprehension Type,Blank Not Used_terminating,Other Violations Entered,Evading Section Charged,Force Type Used to Terminate Pursuit,Canine Involved,Blank Not Used.1_terminating,Terminating Event,Suspect Apprehended,Terminating NCIC_terminating
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,Y,9550,2022-01-01,36,2,1,19,19931,36,2,1,0,0,0,0,75,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,UNKNOWN,UNKNOWN,,1900-01-01,1,0,0,NaN,0,6,5,2018,17,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,2800.2a VC,1,,,NaN,1,N,,10,N,9550
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,Y,9525,2022-01-01,319,1,1,19,16989,320,2,1,0,0,0,0,50,N,0,0,1,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,Trejo,Alexis,M,1991-01-30,11,2,3,CA,0,5,4,2009,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5200 VC,3,,0.0,148a PC,2,,,2800.1a VC,1,N,,7,Y,9525
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,Y,9456,2022-01-01,1333,5,7,20,16764,1333,1,1,0,0,0,0,100,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,4,N,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,0,42,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22348b VC,3,,0.0,NaN,,,,2800.2a VC,1,N,,10,N,9456
3,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,9365,2022-01-01,2202,6,11,48,16515,2202,1,3,1,0,0,100,45,N,0,0,0,N,N,N,Y,0,0,0,0,0,0,0,N,N,N,N,N,N,NaN,DAF,9,3,N,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,2016,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245a PC,1,,0.0,245a PC,1,,Y,2800.2a VC,1,Y,,5,N,9365
4,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,4803,2022-01-01,2151,11,11,48,,,,0,1,1,0,0,1,,0,0,0,N,N,Y,N,0,0,0,0,0,0,NaN,N,N,N,N,N,N,,VF,4,8,,A,Unknown,NaN,,1900-01-01,1,0,0,NaN,0,6,5,2016,8,2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245a PC,1,,0.0,245a PC,1,,Y,2800.2a VC,1,Y,,5,N,9365

In [21]:
main_file['is_duplicate'] = main_file.duplicated(subset='Pursuit Number', keep = False)

In [22]:
main_file.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,Blank Not Used,NCIC Reporting This Rows Info,Date Area Became Involved,Time Area Became Involved,Time Involved Minutes,Distance Involved Miles,County Code,Supervisors ID Number (CHP Only),Time Supervisor Notified,Type of Supervisor Involvement,# of CHP Ground Units Involved,# of CHP Air Units Involved,# of Allied Ground Units Involved,# of Allied Air Units Involved,Max Freeway Speed,Max Surface Speed,Damage to Agency Equipment,Fatal Collision Count,Injury Collision Count,Property Damage Only Collision Count,Injuries due to Collision,Injuries After Pursuit,Did Area Initiate?,Did Area Terminate?,Spike Strip Count,PIT Count,Ramming Count,Boxxing in Count,Remote Engine Disabler Count,Other Forcible Stop Type Count,Other Forcible Stop Description,Area Menu Error Code,Injury Menu Error Code,Initiating Menu Error Code,Terminating Menu Error Code,susp_error,Critique Error Code,Supplemental,Status of Area Report,1st Digit of NCIC,2nd Digit of NCIC,Blank Not Used.1,Weather,is_duplicate
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,Y,9550,2022-01-01,36,2,1,19.0,19931,36,2,1,0,0,0,0,75,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,False
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,Y,9525,2022-01-01,319,1,1,19.0,16989,320,2,1,0,0,0,0,50,N,0,0,1,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,False
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,Y,9456,2022-01-01,1333,5,7,20.0,16764,1333,1,1,0,0,0,0,100,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,4,N,A,False
3,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,9365,2022-01-01,2202,6,11,48.0,16515,2202,1,3,1,0,0,100,45,N,0,0,0,N,N,N,Y,0,0,0,0,0,0,0,N,N,N,N,N,N,NaN,DAF,9,3,N,A,True
4,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,4803,2022-01-01,2151,11,11,48.0,,,,0,1,1,0,0,1,,0,0,0,N,N,Y,N,0,0,0,0,0,0,NaN,N,N,N,N,N,N,,VF,4,8,,A,True

In [23]:
main_file["is_duplicate"].value_counts()

is_duplicate
False    37789
True      3396
Name: count, dtype: int64

In [24]:
main_file['Pursuit Number'].nunique()

39240

In [25]:
type(result)

pandas.core.frame.DataFrame

In [27]:
print(result)

       Pursuit Number Initiating Date  Initiating Time State Status of Report  \
0               20221      2022-01-01               36    CA               F
1               20222      2022-01-01              319    CA               F
2               20223      2022-01-01             1333    UN               F
3               20224      2022-01-01             2151    CA               F
4               20224      2022-01-01             2151    CA               F
...               ...             ...              ...   ...              ...
41180       202413759      2024-08-22              212    UN               F
41181       202413760      2024-08-29                5    CA               F
41182       202413761      2024-09-07              122    CA               F
41183       202413762      2024-09-08              135    CA               F
41184       202413763      2024-09-08             2120    CA               F

      Initiating Agency NCIC Terminating NCIC Multi-Area/Agency Pursuit  \
0                       9550             9550                         N
1                       9525             9525                         N
2                       9456             9456                         N
3                       4803             9365                         Y
4                       4803             9365                         Y
...                      ...              ...                       ...
41180                   1942             1942                         N
41181                   1942             1942                         N
41182                   1942             1942                         N
41183                   1942             1942                         N
41184                   1942             1942                         N

      CHP Participation Requested  Requestor Name Blank Not Used  \
0                               N             NaN              Y
1                               N             NaN              Y
2                               N             NaN              Y
3                               Y  Sgt. Reed # S8              Y
4                               Y  Sgt. Reed # S8              Y
...                           ...             ...            ...
41180                                         NaN              Y
41181                                         NaN              Y
41182                                         NaN              Y
41183                                         NaN              Y
41184                                         NaN              Y

      NCIC Reporting This Rows Info Date Area Became Involved  \
0                              9550                2022-01-01
1                              9525                2022-01-01
2                              9456                2022-01-01
3                              9365                2022-01-01
4                              4803                2022-01-01
...                             ...                       ...
41180                          1942                2024-08-22
41181                          1942                2024-08-29
41182                          1942                2024-09-07
41183                          1942                2024-09-08
41184                          1942                2024-09-08

      Time Area Became Involved  Time Involved Minutes  \
0                            36                      2
1                           319                      1
2                          1333                      5
3                          2202                      6
4                          2151                     11
...                         ...                    ...
41180                       212                      2
41181                         5                      2
41182                       122                      7
41183                       135                      1
41184                      2120                      2

       Distance Involved Miles  County Code Supervisors ID Number (CHP Only)  \
0                            1           19                            19931
1                            1           19                            16989
2                            7           20                            16764
3                           11           48                            16515
4                           11           48
...                        ...          ...                              ...
41180                        4           19
41181                        2           19
41182                        6           19
41183                        1           19
41184                        2           19

      Time Supervisor Notified Type of Supervisor Involvement  \
0                           36                              2
1                          320                              2
2                         1333                              1
3                         2202                              1
4
...                        ...                            ...
41180
41181
41182
41183
41184

       # of CHP Ground Units Involved  # of CHP Air Units Involved  \
0                                   1                            0
1                                   1                            0
2                                   1                            0
3                                   3                            1
4                                   0                            1
...                               ...                          ...
41180                               0                            0
41181                               0                            0
41182                               0                            0
41183                               0                            0
41184                               0                            0

       # of Allied Ground Units Involved  # of Allied Air Units Involved  \
0                                      0                               0
1                                      0                               0
2                                      0                               0
3                                      0                               0
4                                      1                               0
...                                  ...                             ...
41180                                  1                               0
41181                                  1                               0
41182                                  5                               1
41183                                  1                               0
41184                                  1                               0

       Max Freeway Speed  Max Surface Speed Damage to Agency Equipment  \
0                      0                 75                          N
1                      0                 50                          N
2                      0                100                          N
3                    100                 45                          N
4                      0                  1
...                  ...                ...                        ...
41180                120                 50
41181                  0                 70
41182                  0                 70
41183                 80                 50
41184                  0                 70

       Fatal Collision Count  Injury Collision Count  \
0                          0                       0
1                          0                       0
2                          0                       0
3                          0                       0
4                          0                       0
...                      ...                     ...
41180                      0                       0
41181                      0                       0
41182                      0                       0
41183                      0                       0
41184                      0                       0

       Property Damage Only Collision Count Injuries due to Collision  \
0                                         0                         N
1                                         1                         N
2                                         0                         N
3                                         0                         N
4                                         0                         N
...                                     ...                       ...
41180                                     0                         N
41181                                     0                         N
41182                                     0                         N
41183                                     0                         N
41184                                     0                         N

      Injuries After Pursuit Did Area Initiate? Did Area Terminate?  \
0                          N                  Y                   Y
1                          N                  Y                   Y
2                          N                  Y                   Y
3                          N                  N                   Y
4                          N                  Y                   N
...                      ...                ...                 ...
41180                      N                  Y                   Y
41181                      N                  Y                   Y
41182                      N                  Y                   Y
41183                      N                  Y                   Y
41184                      N                  Y                   Y

       Spike Strip Count  PIT Count  Ramming Count  Boxxing in Count  \
0                      0          0              0                 0
1                      0          0              0                 0
2                      0          0              0                 0
3                      0          0              0                 0
4                      0          0              0                 0
...                  ...        ...            ...               ...
41180                  0          0              0                 0
41181                  0          0              0                 0
41182                  0          0              0                 0
41183                  0          0              0                 0
41184                  0          0              0                 0

       Remote Engine Disabler Count  Other Forcible Stop Type Count  \
0                                 0                               0
1                                 0                               0
2                                 0                               0
3                                 0                               0
4                                 0                               0
...                             ...                             ...
41180                             0                               0
41181                             0                               0
41182                             0                               0
41183                             0                               0
41184                             0                               0

      Other Forcible Stop Description Area Menu Error Code  \
0                                 NaN                    N
1                                 NaN                    N
2                                 NaN                    N
3                                   0                    N
4                                 NaN                    N
...                               ...                  ...
41180                             NaN                    N
41181                             NaN                    N
41182                             NaN                    N
41183                             NaN                    N
41184                             NaN                    N

      Injury Menu Error Code Initiating Menu Error Code  \
0                          N                          N
1                          N                          N
2                          N                          N
3                          N                          N
4                          N                          N
...                      ...                        ...
41180                      N                          N
41181                      N                          N
41182                      N                          N
41183                      N                          N
41184                      N                          N

      Terminating Menu Error Code susp_error Critique Error Code Supplemental  \
0                               N          N                   N          NaN
1                               N          N                   N          NaN
2                               N          N                   N          NaN
3                               N          N                   N          NaN
4                               N          N                   N
...                           ...        ...                 ...          ...
41180                           N          N                   N          NaN
41181                           N          N                   N          NaN
41182                           N          N                   N          NaN
41183                           N          N                   N          NaN
41184                           N          N                   N          NaN

      Status of Area Report 1st Digit of NCIC  2nd Digit of NCIC  \
0                       DAF                 9                  5
1                       DAF                 9                  5
2                       DAF                 9                  4
3                       DAF                 9                  3
4                       VF                  4                  8
...                     ...               ...                ...
41180                   VF                  1                  9
41181                   VF                  1                  9
41182                   VF                  1                  9
41183                   VF                  1                  9
41184                   VF                  1                  9

      Blank Not Used.1 Weather Suspect Las Name Suspect First Name  \
0                    N       A          UNKNOWN            UNKNOWN
1                    N       A            Trejo             Alexis
2                    N       A          Unknown                NaN
3                    N       A          Unknown                NaN
4                            A          Unknown                NaN
...                ...     ...              ...                ...
41180                        A              NaN                NaN
41181                        A              NaN                NaN
41182                        A              NaN                NaN
41183                        A              NaN                NaN
41184                        A              NaN                NaN

      Suspect Middle Initial Suspect DOB  Suspect Ethnicity  Suspect Gender  \
0                             1900-01-01                  1               0
1                          M  1991-01-30                 11               2
2                             1900-01-01                  1               0
3                             1900-01-01                  1               0
4                             1900-01-01                  1               0
...                      ...         ...                ...             ...
41180                         1900-01-01                  1               0
41181                         1900-01-01                 20               1
41182                         1998-03-03                 11               1
41183                         1900-01-01                  1               0
41184                         2006-09-20                 11               1

       Suspect ID Type Suspect ID State  Suspect Misc ID Type  \
0                    0              NaN                     0
1                    3               CA                     0
2                    0              NaN                     0
3                    0              NaN                     0
4                    0              NaN                     0
...                ...              ...                   ...
41180                0              NaN                     0
41181                0              NaN                     0
41182                0              NaN                     0
41183                0              NaN                     0
41184                0              NaN                     0

       Driver Disposition  Suspect DUI Status  Suspect Vehicle Year  \
0                       6                   5                  2018
1                       5                   4                  2009
2                       6                   5                     0
3                       6                   5                  2016
4                       6                   5                  2016
...                   ...                 ...                   ...
41180                   0                   5                     0
41181                   0                   1                     0
41182                   0                   5                     0
41183                   0                   5                     0
41184                   0                   5                     0

       Suspect Vehicle Make  Suspect Vehicle Type Unidentified Vehicle Type  \
0                        17                     2
1                         8                     2
2                        42                     2
3                         8                     2
4                         8                     2
...                     ...                   ...                       ...
41180                     1                     2
41181                     1                     3
41182                     1                     2
41183                     1                     2
41184                     1                     2

       Officer Fatality from Collision  Suspect Fatality from Collision  \
0                                  NaN                              NaN
1                                  NaN                              NaN
2                                  NaN                              NaN
3                                  NaN                              NaN
4                                  NaN                              NaN
...                                ...                              ...
41180                              NaN                              NaN
41181                              NaN                              NaN
41182                              NaN                              NaN
41183                              NaN                              NaN
41184                              NaN                              NaN

       Other Fatality from Collision  Officer Severe Injury from Collision  \
0                                NaN                                   NaN
1                                NaN                                   NaN
2                                NaN                                   NaN
3                                NaN                                   NaN
4                                NaN                                   NaN
...                              ...                                   ...
41180                            NaN                                   NaN

In [28]:
print(f"Total rows in main file: {len(main_file)}")
print(f"Total rows after merging: {len(result)}")

Total rows in main file: 41185
Total rows after merging: 41185

In [29]:
print(f"Main file duplicates: {main_file[shared_column].duplicated().sum()}")
print(f"Suspect year duplicates: {suspect_year[shared_column].duplicated().sum()}")
print(f"Total injury duplicates: {total_injury[shared_column].duplicated().sum()}")
print(f"Initiating year duplicates: {initiating_year[shared_column].duplicated().sum()}")
print(f"Terminating info duplicates: {terminating_info[shared_column].duplicated().sum()}")

Main file duplicates: 1945
Suspect year duplicates: 0
Total injury duplicates: 0
Initiating year duplicates: 0
Terminating info duplicates: 0

# I need to create a dictionary
# I need to remove duplicates

In [30]:
ETHNICITY = {
   '1': 'Blank/Unknnown',
   2:  'Alaskan',

}