In [2]:
import requests

In [3]:
import pandas as pd

In [4]:
initiating_year = pd.read_excel('initiating_year_total.xlsx')

In [5]:
main_file = pd.read_excel('main_pursuit_total.xlsx')

In [6]:
#other_violation = pd.read_excel('other_violation_total.xlsx')

In [7]:
suspect_year = pd.read_excel('suspect_year_total.xlsx')

In [8]:
terminating_info = pd.read_excel('terminating_info_total.xlsx')

In [9]:
total_injury = pd.read_excel('total_injury_total.xlsx')

In [10]:
shared_column = "Pursuit Number"

In [18]:
# Set the option to display all columns
pd.set_option('display.max_columns', None)

In [19]:
result = main_file.copy()
result = result.merge(suspect_year, on=shared_column, how="left", suffixes=('', '_suspect'))
result = result.merge(total_injury, on=shared_column, how="left", suffixes=('', '_injury'))
result = result.merge(initiating_year, on=shared_column, how="left", suffixes=('', '_initiating'))
result = result.merge(terminating_info, on=shared_column, how="left", suffixes=('', '_terminating'))
#result = result.merge(other_violation, on=shared_column, how="left", suffixes=('', '_other'))

In [22]:
result['Suspect Ethnicity']

0         1.0
1        11.0
2         1.0
3         1.0
4         1.0
         ...
41180     1.0
41181    20.0
41182    11.0
41183     1.0
41184    11.0
Name: Suspect Ethnicity, Length: 41185, dtype: float64

In [ ]:
# TODO: overwrite result['Suspect Ethnicity'] with a simple integer. Then, downstream
# you can more easily join your ethnicity "key" to this result DataFrame

In [13]:
result.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,...,Most Serious Charged Upon Apprehension Type,Blank Not Used_terminating,Other Violations Entered,Evading Section Charged,Force Type Used to Terminate Pursuit,Canine Involved,Blank Not Used.1_terminating,Terminating Event,Suspect Apprehended,Terminating NCIC_terminating
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,...,1,,,NaN,1.0,N,,10.0,N,9550
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,...,2,,,2800.1a VC,1.0,N,,7.0,Y,9525
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,...,,,,2800.2a VC,1.0,N,,10.0,N,9456
3,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,...,1,,Y,2800.2a VC,1.0,Y,,5.0,N,9365
4,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,...,1,,Y,2800.2a VC,1.0,Y,,5.0,N,9365

In [24]:
main_file['is_duplicate'] = main_file.duplicated(subset='Pursuit Number', keep = False)

In [25]:
main_file.head()

,Pursuit Number,Initiating Date,Initiating Time,State,Status of Report,Initiating Agency NCIC,Terminating NCIC,Multi-Area/Agency Pursuit,CHP Participation Requested,Requestor Name,Blank Not Used,NCIC Reporting This Rows Info,Date Area Became Involved,Time Area Became Involved,Time Involved Minutes,Distance Involved Miles,County Code,Supervisors ID Number (CHP Only),Time Supervisor Notified,Type of Supervisor Involvement,# of CHP Ground Units Involved,# of CHP Air Units Involved,# of Allied Ground Units Involved,# of Allied Air Units Involved,Max Freeway Speed,Max Surface Speed,Damage to Agency Equipment,Fatal Collision Count,Injury Collision Count,Property Damage Only Collision Count,Injuries due to Collision,Injuries After Pursuit,Did Area Initiate?,Did Area Terminate?,Spike Strip Count,PIT Count,Ramming Count,Boxxing in Count,Remote Engine Disabler Count,Other Forcible Stop Type Count,Other Forcible Stop Description,Area Menu Error Code,Injury Menu Error Code,Initiating Menu Error Code,Terminating Menu Error Code,susp_error,Critique Error Code,Supplemental,Status of Area Report,1st Digit of NCIC,2nd Digit of NCIC,Blank Not Used.1,Weather,is_duplicate
0,20221,2022-01-01,36,CA,F,9550,9550,N,N,NaN,Y,9550,2022-01-01,36,2,1,19.0,19931,36,2,1,0,0,0,0,75,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,False
1,20222,2022-01-01,319,CA,F,9525,9525,N,N,NaN,Y,9525,2022-01-01,319,1,1,19.0,16989,320,2,1,0,0,0,0,50,N,0,0,1,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,5,N,A,False
2,20223,2022-01-01,1333,UN,F,9456,9456,N,N,NaN,Y,9456,2022-01-01,1333,5,7,20.0,16764,1333,1,1,0,0,0,0,100,N,0,0,0,N,N,Y,Y,0,0,0,0,0,0,NaN,N,N,N,N,N,N,NaN,DAF,9,4,N,A,False
3,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,9365,2022-01-01,2202,6,11,48.0,16515,2202,1,3,1,0,0,100,45,N,0,0,0,N,N,N,Y,0,0,0,0,0,0,0,N,N,N,N,N,N,NaN,DAF,9,3,N,A,True
4,20224,2022-01-01,2151,CA,F,4803,9365,Y,Y,Sgt. Reed # S8,Y,4803,2022-01-01,2151,11,11,48.0,,,,0,1,1,0,0,1,,0,0,0,N,N,Y,N,0,0,0,0,0,0,NaN,N,N,N,N,N,N,,VF,4,8,,A,True

In [28]:
main_file["is_duplicate"].value_counts()

is_duplicate
False    37789
True      3396
Name: count, dtype: int64

In [29]:
main_file['Pursuit Number'].nunique()

39240

In [14]:
type(result)

pandas.core.frame.DataFrame

In [ ]:
#result.to_excel('combined_pursuit_data.xlsx', index=False)

KeyboardInterrupt:

In [ ]:
print(result)

       Pursuit Number Initiating Date  Initiating Time State Status of Report  \
0               20221      2022-01-01               36    CA               F
1               20222      2022-01-01              319    CA               F
2               20223      2022-01-01             1333    UN               F
3               20224      2022-01-01             2151    CA               F
4               20224      2022-01-01             2151    CA               F
...               ...             ...              ...   ...              ...
41180       202413759      2024-08-22              212    UN               F
41181       202413760      2024-08-29                5    CA               F
41182       202413761      2024-09-07              122    CA               F
41183       202413762      2024-09-08              135    CA               F
41184       202413763      2024-09-08             2120    CA               F

      Initiating Agency NCIC Terminating NCIC Multi-Area/Agency Pursuit  \
0                       9550             9550                         N
1                       9525             9525                         N
2                       9456             9456                         N
3                       4803             9365                         Y
4                       4803             9365                         Y
...                      ...              ...                       ...
41180                   1942             1942                         N
41181                   1942             1942                         N
41182                   1942             1942                         N
41183                   1942             1942                         N
41184                   1942             1942                         N

      CHP Participation Requested  Requestor Name  ...  \
0                               N             NaN  ...
1                               N             NaN  ...
2                               N             NaN  ...
3                               Y  Sgt. Reed # S8  ...
4                               Y  Sgt. Reed # S8  ...
...                           ...             ...  ...
41180                                         NaN  ...
41181                                         NaN  ...
41182                                         NaN  ...
41183                                         NaN  ...
41184                                         NaN  ...

      Most Serious Charged Upon Apprehension Type Blank Not Used_terminating  \
0                                               1
1                                               2
2
3                                               1
4                                               1
...                                           ...                        ...
41180
41181
41182                                           1
41183
41184                                           1

      Other Violations Entered Evading Section Charged  \
0                                                  NaN
1                                           2800.1a VC
2                                           2800.2a VC
3                            Y              2800.2a VC
4                            Y              2800.2a VC
...                        ...                     ...
41180                                              NaN
41181                                              NaN
41182                                              NaN
41183                                              NaN
41184                        Y              2800.2a VC

       Force Type Used to Terminate Pursuit  Canine Involved  \
0                                       1.0                N
1                                       1.0                N
2                                       1.0                N
3                                       1.0                Y
4                                       1.0                Y
...                                     ...              ...
41180                                   0.0
41181                                   0.0
41182                                   0.0
41183                                   0.0
41184                                   0.0

       Blank Not Used.1_terminating Terminating Event Suspect Apprehended  \
0                                                10.0                   N
1                                                 7.0                   Y
2                                                10.0                   N
3                                                 5.0                   N
4                                                 5.0                   N
...                             ...               ...                 ...
41180                                             5.0                   N
41181                                            12.0                   N
41182                                            11.0                   Y
41183                                             5.0                   N
41184                                             1.0                   Y

      Terminating NCIC_terminating
0                             9550
1                             9525
2                             9456
3                             9365
4                             9365
...                            ...
41180                         1942
41181                         1942
41182                         1942
41183                         1942
41184                         1942

[41185 rows x 123 columns]

In [ ]:
print(f"Total rows in main file: {len(main_file)}")
print(f"Total rows after merging: {len(result)}")

Total rows in main file: 41185
Total rows after merging: 41185

In [ ]:
print(f"Main file duplicates: {main_file[shared_column].duplicated().sum()}")
print(f"Suspect year duplicates: {suspect_year[shared_column].duplicated().sum()}")
print(f"Total injury duplicates: {total_injury[shared_column].duplicated().sum()}")
print(f"Initiating year duplicates: {initiating_year[shared_column].duplicated().sum()}")
print(f"Terminating info duplicates: {terminating_info[shared_column].duplicated().sum()}")

Main file duplicates: 1945
Suspect year duplicates: 0
Total injury duplicates: 0
Initiating year duplicates: 0
Terminating info duplicates: 0

In [ ]:
ETHNICITY = {
   '1': 'Blank/Unknnown',
   2:  'Alaskan',

}